server:
 context-path: /bookshop

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    
    

  datasource:
    url: jdbc:mysql://localhost:3306/xuexi
    username: root
    password: root
#    initialize: false
    driver-class-name: com.mysql.jdbc.Driver
  
    
    
mybatis:
  type-aliases-package: com.example.demo.bean
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: debug
    
