server:
 context-path: /bookshop

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xuexi
    username: root
    password: root
#    initialize: false
    driver-class-name: com.mysql.jdbc.Driver
  
    
    
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    root: info
    
